apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restapi-flask
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  project: application
  source:
    repoURL: ssh://git@gitea-ssh.gitea.svc.cluster.local:2222/mateusmullerme/helm-applications.git
    path: restapi-flask
    targetRevision: main
    helm:
      releaseName: flask
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: api